<?php

return [
    "cr" => [
        'San José',
        'Alajuela',
        'Cartago',
        'Heredia',
        'Guanacaste',
        'Puntarenas',
        'Limón',
    ],
    "sv" => [
        'Ahuachapán',
        'Cabañas',
        'Chalatenango',
        'Cuscatlán',
        'La Libertad',
        'La Paz',
        'La Unión',
        'Morazán',
        'San Miguel',
        'San Salvador',
        'San Vicente',
        'Santa Ana',
        'Sonsonate',
        'Usulután',
    ],
    "gt" => [
        'Alta Verapaz',
        'Baja Verapaz',
        'Chimaltenango',
        'Chiquimula',
        'El Progreso',
        'Escuintla',
        'Guatemala',
        'Huehuetenango',
        'Izabal',
        'Jalapa',
        'Jutiapa',
        'Petén',
        'Quetzaltenango',
        'Quiché',
        'Retalhuleu',
        'Sacatepéquez',
        'San Marcos',
        'Santa Rosa',
        'Sololá',
        'Suchitepéquez',
        'Totonicapán',
        'Zacapa',
    ],
    "hn" => [
        'Atlántida',
        'Choluteca',
        'Colón',
        'Comayagua',
        'Copán',
        'Cortés',
        'El Paraíso',
        'Francisco Morazán',
        'Gracias a Dios',
        'Intibucá',
        'Islas de la Bahía',
        'La Paz',
        'Lempira',
        'Ocotepeque',
        'Olancho',
        'Santa Bárbara',
        'Valle',
        'Yoro',
    ],
    "pa" => [
        'Bocas del Toro',
        'Coclé',
        'Colón',
        'Chiriquí',
        'Darién',
        'Herrera',
        'Los Santos',
        'Panamá',
        'Veraguas',
        'Panamá Oeste',
    ]
];

?>
